project: enzyme-stability
name: example_training

datasets: [fireprot]

training:
  num_workers: 12
  learn_rate: 0.001
  epochs: 100
  lr_schedule: true
  # mpnn_learn_rate: 0.001
  # two_stage: true

model:
  hidden_dims: [64, 32]
  subtract_mut: true
  num_final_layers: 2
  freeze_weights: true
  load_pretrained: true
  lightattn: true